# Generated by Django 3.2.5 on 2021-07-21 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tribe', '0002_members_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tribe.tribe')),
            ],
        ),
    ]
